### ISSUE TITLE
In memory connector tests not working with async operations

### ISSUE THREAD

**Issue by carlos-silva24** [smallrye/smallrye-reactive-messaging#1082]
Greetings!

I was trying to update the test **testWithMessages** that can be found here: https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-in-memory/src/test/java/io/smallrye/reactive/messaging/connectors/InMemoryConnectorTest.java

I'm running the test on a quarkus project (using the **smallrye-reactive-messaging-in-memory 2.4 version**). Because of that, I'm not using the beanManager to retrieve the InMemoryConnector, I'm injecting the connector like this:

```
@QuarkusTest //used on my test class
...
@Inject @Any
InMemoryConnector connector;
```

I was trying to test the following code by adding an implementation for the **bar** channel.

```
@ApplicationScoped
public static class MyBeanReceivingMessage {

    @Incoming("foo")
    @Outgoing("bar")
    public Message<String> process(Message<String> s) {
        return s.withPayload(s.getPayload().toUpperCase());
    }
}
```

The **bar** implementation:

```
@Incoming("bar")
public Message<List<String>> process1(Message<List<String>> s) {
    return s.withPayload(Arrays.asList("HELLO2"));
}
```

This gives me an error saying:
```
javax.enterprise.inject.spi.DefinitionException: SRMSG00051: Invalid method annotated with @Incoming: com.bmw.cc.nav.gnss.rdr.integration.ConnectorsIntegrationTest$MyBeanReceivingMessage#process1 - The signature is not supported as it requires 'blocking' acknowledgment, return a CompletionStage<Message<?> instead.
	at io.smallrye.reactive.messaging.MediatorConfigurationSupport.validateSubscriber(MediatorConfigurationSupport.java:203)
	at io.smallrye.reactive.messaging.MediatorConfigurationSupport.validate(MediatorConfigurationSupport.java:84)
	at io.quarkus.smallrye.reactivemessaging.deployment.QuarkusMediatorConfigurationUtil.create(QuarkusMediatorConfigurationUtil.java:76)
	at io.quarkus.smallrye.reactivemessaging.deployment.SmallRyeReactiveMessagingProcessor.build(SmallRyeReactiveMessagingProcessor.java:350)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
```

I tried to fix it by using the CompletionStage like this:
```
@Incoming("bar")
public CompletionStage<Message<List<String>>> process1(Message<List<String>> s) {
    AtomicBoolean acked = new AtomicBoolean();
    Message<List<String>> msg = Message.of(Arrays.asList("Hello"), () -> {
        acked.set(true);
        CompletableFuture<Void> future = new CompletableFuture<>();
        future.complete(null);
        return future;
    });

    return CompletableFuture.supplyAsync(() -> msg);
}
```

I managed to compile the code and I can see the channel receiving the messages, but when I try to access the connector sink to check if the messages were received, there are no received messages.

Here is my test implementation:

```
@Test
public void testWithMessages() {
    InMemorySource<Message<String>> foo = connector.source("foo");
    InMemorySink<List<String>> bar = connector.sink("bar");

    AtomicBoolean acked = new AtomicBoolean();
    Message<String> msg = Message.of("hello", () -> {
        acked.set(true);
        CompletableFuture<Void> future = new CompletableFuture<>();
        future.complete(null);
        return future;
    });
    foo.send(msg);
    assertThat(bar.received()).hasSize(1);
    assertThat(acked).isTrue();
}
```

If I remove the **@Incoming("bar")** implementation the test works, otherwise the **received** count never changes.

Can someone help me to figure out what is happening here and why?

Thank you in advance.

**Comment by cescoffier** [comment]
The following code is invalid:

```
@Incoming("bar")
public Message<List<String>> process1(Message<List<String>> s) {
    return s.withPayload(Arrays.asList("HELLO2"));
}
```

The in-memory connector requires receiving messages in a channel normally handled by a connector. It's not your case, as, from my understanding, your method is a consumer method. In this case, you can't use the in-memory connector (because that's not a connector). You will need to collect the items in your method and provides a method to retrieve them:

```java
List<String> list = new CopyOnWriteArrayList<>();

@Incoming("bar")
public CompletionStage<Void> process1(Message<List<String>> s) {
     list.addAll(s);
    return s.ack();
}

public List<String> getList() { return list; }

```

You may want to only enable the collection in tests, as it may lead to OOM if the list is never cleared.
