### ISSUE TITLE
Unable to reconnect producer after broker failure

### ISSUE THREAD

**Issue by vsevel** [smallrye/smallrye-reactive-messaging#1140]
I have implemented https://quarkus.io/guides/amqp using:
- a cluster of 2 interconnect, connected using link routes to
- a cluster of 2 AMQ brokers

The interconnect and broker processes run in openshift 4. the client runs outside.
When I run the application, I first kill a broker. the application continues sending and receiving messages.
I wait until the killed broker is restarted and ready, then I kill the 2nd broker.
thereafter I get the following exception on each send:
```
2021-03-30 17:02:50,786 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-9) Uncaught exception received by Vert.x: java.lang.IllegalStateException: send not allowed after the sender is closed.
        at org.apache.qpid.proton.engine.impl.SenderImpl.sendNoCopy(SenderImpl.java:86)
        at io.vertx.proton.impl.ProtonSenderImpl.send(ProtonSenderImpl.java:91)
        at io.vertx.proton.impl.ProtonSenderImpl.send(ProtonSenderImpl.java:56)
        at io.vertx.amqp.impl.AmqpSenderImpl.lambda$doSend$6(AmqpSenderImpl.java:181)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

this exception gets printed over and over again for every tick, even after the killed broker has been restarted.
eventually I kill the client and restart it, then  sending and receiving resume normally.

is there an issue in the client, or is the code too naive and not expected to work by design in this type of situation?

**Comment by cescoffier** [comment]
@gemmellr any idea?

**Comment by gemmellr** [comment]
Knowing the use case from above description (and other issues here/elsewhere), the router will be closing the sender links when the broker they are link-routed to goes away (and/or isnt there when a new link is trying to be created). From the description, it sounds SRM may have handled this in one case but not another. From the stacktrace, presumably a particular sender link was closed and yet SRM (or vertx-amqp-client) somehow isnt aware of this and so continues to try using it, which is a case proton itself will throw.

**Comment by alexlitovsky** [comment]
I think I have a related issue with Azure Event Hub, which aggressively closes idle connections after 5 minutes: https://github.com/smallrye/smallrye-reactive-messaging/issues/1588

Just wondering if I need to submit this issue with vertx or is this the right place?

**Comment by cescoffier** [comment]
I would say vertx. In RM we are a bit too far away from the connection. We can try to retry sending, but that may not be efficient.

**Comment by alexlitovsky** [comment]
Thanks @cescoffier , I will submit it to vertx.
