### ISSUE TITLE
Cycle detection wrongly reports joins as Cycles

### ISSUE THREAD

**Issue by Omega1001** [smallrye/smallrye-reactive-messaging#1229]
If I build an app where Messages are put on a reactive messaging stream that branches onto two or more services and then joins in a common Terminator etc., a  loop is detected where there is none:

The Setup is as follows:
![setup](https://user-images.githubusercontent.com/10009846/120071826-28aab880-c091-11eb-8d7b-f9475d4ca749.png)
Apparently it contains no loop and should work without problems 

Minimal (not) Working example that matches the structure is available [here](https://github.com/Omega1001/smallyryCycleError/tree/master/smallry%20Cycle%20error)

JDK is OpenJDK 16.0.1 compiling Java 11 Code
Platform is Quarkus (1.13.6.Final).
Reactive Messaging dependency is quarkus-smallrye-reactive-messaging from Quarkus BOM

The provided Example works fine if you either:
- exclude the Join
- reroute the output of Service 2 to an other topic (like "join2" in example)

so it is not the fork causing the problem, but the join

Expected behavior:
The code runs without error

Actual behavior:
An error is thrown on startup

The error:
```
2021-05-29 15:23:57,400 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.reactive.messaging.wiring.CycleException: Cycle detected between ProcessingMethod{method:'service2', incoming:'fork', outgoing:'join'} and a downstream component SubscriberMethod{method:'join', incoming:'join'}
	at io.smallrye.reactive.messaging.wiring.Graph.detectCycles(Graph.java:205)
	at io.smallrye.reactive.messaging.wiring.Graph.detectCycles(Graph.java:208)
	at io.smallrye.reactive.messaging.wiring.Graph.detectCycles(Graph.java:208)
	at io.smallrye.reactive.messaging.wiring.Graph.detectCycles(Graph.java:197)
	at io.smallrye.reactive.messaging.wiring.Graph.<init>(Graph.java:32)
	at io.smallrye.reactive.messaging.wiring.Wiring.resolve(Wiring.java:154)
	at io.smallrye.reactive.messaging.wiring.Wiring_Subclass.resolve$$superaccessor5(Wiring_Subclass.zig:884)
	at io.smallrye.reactive.messaging.wiring.Wiring_Subclass$$function$$5.apply(Wiring_Subclass$$function$$5.zig:29)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.smallrye.reactive.messaging.wiring.Wiring_Subclass.resolve(Wiring_Subclass.zig:842)
	at io.smallrye.reactive.messaging.wiring.Wiring_ClientProxy.resolve(Wiring_ClientProxy.zig:126)
	at io.smallrye.reactive.messaging.extension.MediatorManager.start(MediatorManager.java:184)
	at io.smallrye.reactive.messaging.extension.MediatorManager_Subclass.start$$superaccessor11(MediatorManager_Subclass.zig:1767)
	at io.smallrye.reactive.messaging.extension.MediatorManager_Subclass$$function$$11.apply(MediatorManager_Subclass$$function$$11.zig:29)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.smallrye.reactive.messaging.extension.MediatorManager_Subclass.start(MediatorManager_Subclass.zig:1725)
	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.start(MediatorManager_ClientProxy.zig:282)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:40)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass.onApplicationStart$$superaccessor2(SmallRyeReactiveMessagingLifecycle_Subclass.zig:364)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass$$function$$2.apply(SmallRyeReactiveMessagingLifecycle_Subclass$$function$$2.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass.onApplicationStart(SmallRyeReactiveMessagingLifecycle_Subclass.zig:321)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:111)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:268)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:763)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:831)

2021-05-29 15:23:57,402 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
Quarkus application exited with code 1

```

**Comment by Omega1001** [comment]
I did some more Debugging on this.
Here is what I found out:

**The Cause of the Problem**
The problem is located in the Class `io.smallrye.reactive.messaging.wiring.Graph` which is part of the `io.smallrye.reactive:smallrye-reactive-messaging-provider` project.

There, the `detectCycles()` method is used to find out if the Graph has a cycle in it.
It does that by rooting the Graph at the initial input an the traverses the resulting tree.
While doing that, it remembers what components it already traversed in a set.
If a component is visited, that is already recorded in the set, it is considered a loop.

Now if a Component is part of more than one path, the component is first added to the set when traversing the first path and is then already existent when the second path is traversed.
It the detects a loop that isn't ther.

To fix that, the set of already visited Components should be specific to the path that is being traversed.
Specifically, when calling the recursion to traverse a subtree it should work with a copy of the set containing only notes that have been seen up to this point, not containing any notes seen while traversing any of the previously traversed sibling trees.

**My suggested Solution**
To isolate the processing of the branches, I would pass a copy of the set instead of reusing the current one.

Specifically alter 
```
Graph.java Line 201-211
private void detectCycles(Set<Wiring.Component> traces, Wiring.Component component) throws CycleException {
        traces.add(component);
        for (Wiring.Component downstream : component.downstreams()) {
            if (traces.contains(downstream)) {
                throw new CycleException(component, downstream);
            } else {
                traces.add(downstream);
                detectCycles(traces, downstream);
            }
        }
    }
```
to
```
Graph.java Line 201-211
private void detectCycles(Set<Wiring.Component> traces, Wiring.Component component) throws CycleException {
        traces.add(component);
        for (Wiring.Component downstream : component.downstreams()) {
            if (traces.contains(downstream)) {
                throw new CycleException(component, downstream);
            } else {
                traces.add(downstream);
 --->        detectCycles(new HashSet<>(traces), downstream);   <---
            }
        }
    }
```
You might want to optimize that a little by only passing a copy if there is more then one downstream

**Comment by cescoffier** [comment]
Thanks for the analysis! Looks good, fancy a PR?

**Comment by Omega1001** [comment]
Glad if I can help.

I'm good at the moment, but thanks anyway.
