### ISSUE TITLE
smallrye-reactive-messaging-rabbitmq:3.9.1 config issues in helidon-mp

### ISSUE THREAD

**Issue by btcdevops-apps** [smallrye/smallrye-reactive-messaging#1433]
**MP Implementation**: Helidon-MP 2.3.3
I am trying to consume this artifact in helidon mp, however the application crashes at start up. The logs below indicates that ConfiguredChannelFactory.initialize() in smallrye-reactive-messaging-provider  is using the spi implementation thus unable to load the entries in the microprofile-config.properties or application.yaml file.

**Is there any additional steps required to use this artifact without necessarily attempting to hack it?**

`2021.09.27 16:23:54 INFO io.helidon.common.LogConfig Thread[main,5,main]: Logging at initialization configured using classpath: /logging.properties
2021.09.27 16:23:56 INFO io.smallrye.reactive.messaging.provider Thread[main,5,main]: SRMSG00224: Analyzing mediator bean: Managed Bean [class me.sheryf.mp.quickstart.RMQOutboundMessage] with qualifiers [@Any @Default]
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException
        at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:38)
        at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
        at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:505)
        at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:297)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:249)
        at io.helidon.microprofile.server.ServerImpl.start(ServerImpl.java:85)
        at me.sheryf.mp.quickstart.DemoMain.startServer(DemoMain.java:14)
        at me.sheryf.mp.quickstart.DemoMain.main(DemoMain.java:10)
Caused by: javax.enterprise.event.ObserverException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:103)
        at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
        at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
        at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/microprofile/config/ConfigValue
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$extractConfigurationFor$3(ConfiguredChannelFactory.java:105)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.extractConfigurationFor(ConfiguredChannelFactory.java:94)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:121)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory$Proxy$_$$_WeldClientProxy.initialize(Unknown Source)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at io.smallrye.reactive.messaging.extension.MediatorManager.start(MediatorManager.java:189)
        at io.smallrye.reactive.messaging.extension.MediatorManager$Proxy$_$$_WeldClientProxy.start(Unknown Source)
        at io.smallrye.reactive.messaging.extension.ReactiveMessagingExtension.afterDeploymentValidation(ReactiveMessagingExtension.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
        ... 22 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.microprofile.config.ConfigValue
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 38 more
`

**Comment by cescoffier** [comment]
You need an implementation of MicroProfile Config 2.0. I don't know which version is implemented by Helidon.

**Comment by cescoffier** [comment]
BTW, we don't use the SPI implementation: org/eclipse/microprofile/config/ConfigValue is part of the spect.

**Comment by radcortez** [comment]
Hi @btcdevops-apps,

`ConfigValue` is an MP Config 2.0 API. It seems that the Helidon version you are using only supports 1.4: https://github.com/oracle/helidon/blob/2.3.3/dependencies/pom.xml#L99.
