### ISSUE TITLE
Receving AMQP messages gives errors

### ISSUE THREAD

**Issue by misl** [smallrye/smallrye-reactive-messaging#145]
To get a better grasp of how to use/ingrate AMQP into my own solution I started a simple example project [amqp-quickstart](https://github.com/misl/smallrye-reactive-messaging/tree/amqp-example/examples/amqp-quickstart). This example is very similar to the existing Kafka and MQTT quickstarts.

Unfortunately when running it I get the following error:
```
[vert.x-eventloop-thread-0] ERROR acme.Receiver#consume - Error caught during the stream processing
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: io.vertx.amqp.AmqpReceiverOptions.setAutoAcknowledgement(Z)Lio/vertx/amqp/AmqpReceiverOptions;
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.vertx.axle.AsyncResultCompletionStage.lambda$toCompletionStage$0(AsyncResultCompletionStage.java:18)
	at io.vertx.axle.amqp.AmqpClient$1.handle(AmqpClient.java:112)
	at io.vertx.axle.amqp.AmqpClient$1.handle(AmqpClient.java:109)
	at io.vertx.amqp.impl.AmqpConnectionImpl.lambda$null$3(AmqpConnectionImpl.java:107)
	at io.vertx.proton.impl.ProtonConnectionImpl.fireRemoteOpen(ProtonConnectionImpl.java:368)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:111)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:386)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:235)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:125)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:364)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodError: io.vertx.amqp.AmqpReceiverOptions.setAutoAcknowledgement(Z)Lio/vertx/amqp/AmqpReceiverOptions;
	at io.smallrye.reactive.messaging.amqp.AmqpConnector.lambda$getPublisherBuilder$7(AmqpConnector.java:177)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
```
I find this error quite puzzling. It does not seem to be a missing dependency since the Class `AmqpReceiverOptions` is known but the method `setAutoAcknowledgement()` is not. So maybe an incorrect dependency version? But still, I get no error in my IDE or at buildtime, only at runtime. 

Anyone a clue?

Sending messages seems to work. I get no errors while sending and the MQ broker stats shows incoming messages.

**Comment by misl** [comment]
To resolve this I had to explicitly include a bugfix version 3.7.1.1 of vertx-amqp-client in the amqp-quickstart module.

**Comment by misl** [comment]
Shouldn't this be documented somewhere? I guess every smallrye amqp client will run into this.

**Comment by cescoffier** [comment]
Hum, it looks like a dependency error. You need 3.7.1.1 (yes 2 .1) for the vertx-amqp-client.

Let me try to reproduce it.

**Comment by cescoffier** [comment]
Doesn’t the connector depend on 3.7.1.1 already?

**Comment by misl** [comment]
Yes the connector has that dependency too. That's where I got it from.

**Comment by cescoffier** [comment]
What I don't understand is why it's not resolved as a transitive dependency. Is the last `.1`too much for Maven?

**Comment by misl** [comment]
Almost looks like it. Try a `mvn help:effective-pom` of the amqp-quickstart without the additional 3.7.1.1 dependency. Then the effective pom shows 3.7.1 to be present. 

Just like you I don't get it. According to [Maven versioning](https://cwiki.apache.org/confluence/display/MAVENOLD/Versioning) maven 3+ should allow for more than 3 version number parts.

Let's hope vert.x comes soon with another 'real' update ;-)

**Comment by cescoffier** [comment]
Vert.x 3.8 is planned for July.

**Comment by cescoffier** [comment]
I've updated to 3.8.0
