### ISSUE TITLE
AMQP - Intermittent errors sending messages to Azure Service Bus due to closed idle connections

### ISSUE THREAD

**Issue by alexlitovsky** [smallrye/smallrye-reactive-messaging#1588]
I have a Quarkus 2.6.3 application that sends messages via an `Emitter` to Azure Service Bus
It uses smallrye-reactive-messaging-amqp 3.13.0

Azure Service Bus disconnects idle connections after 5 minutes.  That's just how it is.
Right after the Azure Service Bus drops the idle connection, attempts to send a message fail with the Exception below.
Eventually the system recovers and is able to send messages again, but this leaves it in bad state for several minutes.

**Code:**
```
@ApplicationScoped
public class MessageSender {
	
    @Inject
    @Channel("my-queue")
    Emitter<MyJsonPayload> emitter;
	
    public void sendMessage() {
         emitter.send(createPayload());
    }
}
```

**Configuration:**
```
amqp-host=my-namespace.servicebus.windows.net
amqp-port=5671
amqp-use-ssl=true
amqp-username=*********
amqp-password=*********
amqp-reconnect-interval=5

mp.messaging.outgoing.my-queue.connector=smallrye-amqp
mp.messaging.outgoing.my-queue.use-anonymous-sender=false
mp.messaging.outgoing.my-queue.address=my-queue
```

**Exception**:
```
2022-01-28 15:57:34,221 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-6) Uncaught exception received by Vert.x: java.lang.IllegalStateException: send not allowed after the sender is closed.
	at org.apache.qpid.proton.engine.impl.SenderImpl.sendNoCopy(SenderImpl.java:86)
	at io.vertx.proton.impl.ProtonSenderImpl.send(ProtonSenderImpl.java:91)
	at io.vertx.proton.impl.ProtonSenderImpl.send(ProtonSenderImpl.java:56)
	at io.vertx.amqp.impl.AmqpSenderImpl.lambda$doSend$6(AmqpSenderImpl.java:183)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This is preceded by this stack-trace that indicates that the connection was closed by Azure Service Bus:
```
2022-01-28 15:05:15,894 ERROR [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16214: AMQP Connection failure: java.lang.Exception: Connection disconnected
	at io.vertx.amqp.impl.AmqpConnectionImpl.onDisconnect(AmqpConnectionImpl.java:158)
	at io.vertx.amqp.impl.AmqpConnectionImpl.lambda$null$3(AmqpConnectionImpl.java:113)
	at io.vertx.proton.impl.ProtonConnectionImpl.lambda$getDefaultSession$6(ProtonConnectionImpl.java:263)
	at io.vertx.proton.impl.ProtonSessionImpl.fireRemoteClose(ProtonSessionImpl.java:276)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:135)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:98)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:418)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:394)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:156)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The remote connection closure needs to be handled more gracefully.

Unfortunately I can't create a test-case to reproduce this.  It's intermittent, and involves closing the connection by the broker.

**Comment by cescoffier** [comment]
Not great, but did you try with a MitinyEmitter and with an onFailure().retry()?

Do you know how the system fixes itself? Is it due to an application restart?

**Comment by alexlitovsky** [comment]
Thanks for the MutinyEmitter tip.  I will try that.  I'm trying to setup a repeatable scenario so that I can experiment and at least get more details.

The Emitter recovers by itself after a few minutes.  No restarts are needed.

**Comment by alexlitovsky** [comment]
@cescoffier I created a reproducer:  https://bitbucket.org/alexlitovsky1/vertx-amqp-emitter-bug

A few interesting things:
1. It only fails if my messages are sent with a period > 10 minutes.  This leads me to believe that it's not the 5 minutes idle connection timeout of ASB, but the 10 minute idle link timeout:  https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-troubleshoot#link-is-closed
2. When this condition happens, the error callback is not being triggered (unless I'm doing something wrong):
```
emitter.send(new Payload("Hello world!")).exceptionally(t -> {
   // never gets here
   LOGGER.error("error sending message", t);
   return null;
});
```

As you had suggested on #1140, I will submit this to vertx amqp.
I will also try good old JMS for sending instead.

**Comment by cescoffier** [comment]
Thanks for the reproducer. I will have a look to see if we can do something at the connector level.

**Comment by alexlitovsky** [comment]
Related issue submitted to vertx:  https://github.com/vert-x3/vertx-amqp-client/issues/77

**Comment by cescoffier** [comment]
Thanks for the repoducer. I got a hack that made it work:

```
2022-02-01 10:52:17,838 DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16222: Retrieved credits for channel `test`: 1000
Sending message...
2022-02-01 10:52:21,029 DEBUG [io.sma.rea.mes.amqp] (executor-thread-0) SRMSG16211: Sending AMQP message to address `test`
Message sent successfully
2022-02-01 10:52:21,165 INFO  [com.ale.bug.amq.MessageSender] (vert.x-eventloop-thread-0) Message sent
Sending message...
2022-02-01 11:03:21,128 DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16211: Sending AMQP message to address `test`
Message sent successfully
2022-02-01 11:03:21,254 INFO  [com.ale.bug.amq.MessageSender] (vert.x-eventloop-thread-0) Message sent
Sending message...
2022-02-01 11:14:21,136 DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16211: Sending AMQP message to address `test`
Message sent successfully
2022-02-01 11:14:21,263 INFO  [com.ale.bug.amq.MessageSender] (vert.x-eventloop-thread-0) Message sent
Sending message...
2022-02-01 11:25:22,114 DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16211: Sending AMQP message to address `test`
Message sent successfully
2022-02-01 11:25:22,240 INFO  [com.ale.bug.amq.MessageSender] (vert.x-eventloop-thread-0) Message sent
Sending message...
2022-02-01 11:36:22,112 DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16211: Sending AMQP message to address `test`
Message sent successfully
2022-02-01 11:36:22,243 INFO  [com.ale.bug.amq.MessageSender] (vert.x-eventloop-thread-0) Message sent
Sending message...
2022-02-01 11:47:22,092 DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16211: Sending AMQP message to address `test`
Message sent successfully
2022-02-01 11:47:22,217 INFO  [com.ale.bug.amq.MessageSender] (vert.x-eventloop-thread-0) Message sent
```

**Comment by cescoffier** [comment]
Opened https://github.com/vert-x3/vertx-amqp-client/pull/78 which would let me fix this issue in a less hackish way...

**Comment by cescoffier** [comment]
I opened a PR (not ready because of a huge hack waiting for a vert.x release), but you can try with it.
You would need to build the project and then add the following dependency in your reproducer:

```xml
<dependency>
	<groupId>io.smallrye.reactive</groupId>
	<artifactId>smallrye-reactive-messaging-amqp</artifactId>
	<version>3.14.0-SNAPSHOT</version>
</dependency>
```
