### ISSUE TITLE
AMQP - Support passing other config options to Vertx AmqpClient

### ISSUE THREAD

**Issue by alexlitovsky** [smallrye/smallrye-reactive-messaging#1589]
Vertx AmqpClientOptions supports a bunch of useful options, such as `idleTimeout`:
https://github.com/vert-x3/vertx-amqp-client/blob/master/src/main/java/io/vertx/amqp/AmqpClientOptions.java

However, SRM only allows the app to use a subset of them.
https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpClientHelper.java#L118

Please expand AmqpClientHelper to allow applications to set all options that Vertx supports.

**Comment by cescoffier** [comment]
You can pass your own AmqpClientOptions provider. Thus, you can pass all the options you want.
See https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.4/amqp/amqp.html#amqp-customization

**Comment by alexlitovsky** [comment]
Thank you!  I should have RTFM.

The example didn't work for me with `@Identifier("my-named-options")`.  It did work once I changed it to `@Named("my-named-options")`.

```
Caused by: java.lang.IllegalStateException: SRMSG16000: Cannot find a io.vertx.amqp.AmqpClientOptions bean named my-named-options
	at io.smallrye.reactive.messaging.amqp.AmqpClientHelper.createClientFromClientOptionsBean(AmqpClientHelper.java:48)
	at io.smallrye.reactive.messaging.amqp.AmqpClientHelper.createClient(AmqpClientHelper.java:29)
	at io.smallrye.reactive.messaging.amqp.AmqpConnector.getSubscriberBuilder(AmqpConnector.java:242)
	at io.smallrye.reactive.messaging.amqp.AmqpConnector_Subclass.getSubscriberBuilder$$superforward1(Unknown Source)
	at io.smallrye.reactive.messaging.amqp.AmqpConnector_Subclass$$function$$11.apply(Unknown Source)
```

**Comment by cescoffier** [comment]
We support both. Which version of reactive messaging are you using?

**Comment by alexlitovsky** [comment]
3.13.0

**Comment by cescoffier** [comment]
Can you provide a reproducer?

**Comment by cescoffier** [comment]
Wow... that's interesting. I asked @mkouba as it looks like something odd in Arc (it works with Weld).

**Comment by cescoffier** [comment]
We found the issue, and it's a missing index in smallrye-common annotation. I will fix that this morning.

**Comment by cescoffier** [comment]
See https://github.com/smallrye/smallrye-common/pull/129.
