### ISSUE TITLE
smallrye-rabbitmq: Unclear error message on IncomingRabbitMQMessage.getPayload()

### ISSUE THREAD

**Issue by IsSkyfalls** [smallrye/smallrye-reactive-messaging#1642]
When consuming messages from a rabbitmq queue, I got this horrible stacktrace.
```text
2022-03-04 22:08:24,899 ERROR [io.sma.rea.mes.rabbitmq] (pool-1-thread-1) out: io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
	[Exception 0] java.lang.ClassCastException: class [B cannot be cast to class io.vertx.core.json.JsonObject ([B is in module java.base of loader 'bootstrap'; io.vertx.core.json.JsonObject is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @65e98b1c)
	[Exception 1] io.smallrye.reactive.messaging.providers.ProcessingException: SRMSG00103: Exception thrown when calling the method xyz.skyfalls.placeholder.CrawlRequestProcessor#process
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:89)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onFailure(UniOnItemOrFailureFlatMap.java:65)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:28)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToMulti.subscribe(UniOnItemTransformToMulti.java:39)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:39)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:193)
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.tryEmit(MultiFlatMapOp.java:230)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onItem(MultiFlatMapOp.java:607)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onItem(UniToMultiPublisher.java:93)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:37)
	at io.smallrye.mutiny.groups.UniOnNull.lambda$failWith$1(UniOnNull.java:46)
	at io.smallrye.context.impl.wrappers.SlowContextualBiConsumer.accept(SlowContextualBiConsumer.java:21)
	at io.smallrye.mutiny.groups.UniOnItem.lambda$transformToUni$4(UniOnItem.java:178)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.quarkus.smallrye.reactivemessaging.runtime.devmode.DevModeSupportConnectorFactoryInterceptor.lambda$intercept$0(DevModeSupportConnectorFactoryInterceptor.java:42)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.quarkus.smallrye.reactivemessaging.runtime.devmode.ReactiveMessagingHotReplacementSetup$OnMessage$1.run(ReactiveMessagingHotReplacementSetup.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: io.smallrye.reactive.messaging.providers.ProcessingException: SRMSG00103: Exception thrown when calling the method xyz.skyfalls.placeholder.CrawlRequestProcessor#process
		at io.smallrye.reactive.messaging.providers.ProcessorMediator.handlePostInvocationWithMessage(ProcessorMediator.java:353)
		at io.smallrye.reactive.messaging.providers.ProcessorMediator.lambda$processMethodReturningAUniOfMessageAndConsumingIndividualItem$41(ProcessorMediator.java:374)
		at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
		at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
		... 42 more
	Caused by: java.lang.ClassCastException: class [B cannot be cast to class io.vertx.core.json.JsonObject ([B is in module java.base of loader 'bootstrap'; io.vertx.core.json.JsonObject is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @65e98b1c)
		at xyz.skyfalls.placeholder.CrawlRequestProcessor.process(CrawlRequestProcessor.java:21)
		at xyz.skyfalls.placeholder.CrawlRequestProcessor_Subclass.process$$superforward1(Unknown Source)
		at xyz.skyfalls.placeholder.CrawlRequestProcessor_Subclass$$function$$1.apply(Unknown Source)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
		at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
		at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
		at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
		at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
		at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
		at xyz.skyfalls.placeholder.CrawlRequestProcessor_Subclass.process(Unknown Source)
		at xyz.skyfalls.placeholder.CrawlRequestProcessor_ClientProxy.process(Unknown Source)
		at xyz.skyfalls.placeholder.CrawlRequestProcessor_SmallRyeMessagingInvoker_process_6f6e0a5c5ae431d64246758e5015ca5fbc165d76.invoke(Unknown Source)
		at io.smallrye.reactive.messaging.providers.AbstractMediator.invoke(AbstractMediator.java:91)
		at io.smallrye.reactive.messaging.providers.ProcessorMediator.lambda$processMethodReturningAUniOfMessageAndConsumingIndividualItem$40(ProcessorMediator.java:373)
		at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
		at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
		... 40 more
	[CIRCULAR REFERENCE:java.lang.ClassCastException: class [B cannot be cast to class io.vertx.core.json.JsonObject ([B is in module java.base of loader 'bootstrap'; io.vertx.core.json.JsonObject is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @65e98b1c)]
```

I spent a couple of minutes digging through the stacktrace but really isn't a lot of information here.
It turns out the other producer submitted the message with header "content-type" instead of "content_type". The rabbitmq connector just refuses to convert the message to JsonObject because of the wrong header. I only realized this out after going through the documentation again.

In [IncomingRabbitMQMessage](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-rabbitmq/src/main/java/io/smallrye/reactive/messaging/rabbitmq/IncomingRabbitMQMessage.java#L112), there's a comment saying "Throw a class cast exception if it cannot be converted." Is there a reason for this? I would say that logging a proper error/warning when the target type and header mismatch(in convertPayload) is definitely more intuitive than this.

I only tested this with quarkus(version 2.7.2.Final), so maybe it's messing up the log message somehow. But still, I consider this as a valid issue. I can probably do a pr later if that's needed.

**Comment by cescoffier** [comment]
It looks like it expect a io.vertx.core.json.JsonObject, but it receives a byte[]? What's your method signature?

**Comment by IsSkyfalls** [comment]
```java
@Incoming("in")
@Outgoing("out")
public Uni<Message<CrawlResponse>> process(Message<JsonObject> message){
}
```

It recieves a byte[] because the header is incorrect(- instead of _). And `convertPayload()` just fallsback to byte[] in that case.
```java
// If there is a content encoding specified, we don't try to unwrap
        if (contentEncoding == null) {
            // Do our best with text and json
            if (HttpHeaderValues.APPLICATION_JSON.toString().equalsIgnoreCase(contentType)) {
                // This could be  JsonArray, JsonObject, String etc. depending on buffer contents
                return body.toJson();
            } else if (HttpHeaderValues.TEXT_PLAIN.toString().equalsIgnoreCase(contentType)) {
                return body.toString();
            }
        }
        // Otherwise fall back to raw byte array
        return body.getBytes();
```
I'm just wandering why isn't the method signature respected here. Why does the header matter if we explicitly want a JsonObject.

**Comment by cescoffier** [comment]
Yeah, that sounds like a bug in the RabbitMQ connector.

**Comment by IsSkyfalls** [comment]
So the problem actually lies in the `com.rabbitmq:amqp-client` library. It always uses the `content_type`attribute, and it's not customizable.

From https://www.rabbitmq.com/tutorials/amqp-concepts.html
> Messages in the AMQP 0-9-1 model have attributes. Some attributes are so common that the AMQP 0-9-1 specification defines them and application developers do not have to think about the exact attribute name. Some examples are
>
> - Content type
> - Content encoding
> 
> Protocol peers typically use the "content-type" and "content-encoding" fields to communicate this information, but this is **by convention only**.

My suggestion: If the library can use whatever they want for the attributes, implementing a flag that disables the attribute check is probably a good idea. Or we could just ditch the check completely and only use the genetic type.

**Comment by IsSkyfalls** [comment]
Done in #1667
