### ISSUE TITLE
AMQP - when using multiple Emitters intermitently fails to retrieve credits on startup

### ISSUE THREAD

**Issue by alexlitovsky** [smallrye/smallrye-reactive-messaging#1662]
**Scenario**
Quarkus application using SRM AMQP 3.15.0
Application uses Emitters to send messages to multiple Queues on the same Azure Service Bus

**Problem**
On startup, SRM silently fails to obtain credits for **some** of the channels.  This is sporadic but frequent.
This does not cause the startup to fail.  It also does not recover.
Attempts to send messages using these Emitters fail.

**Reproducer**
git clone https://bitbucket.org/alexlitovsky1/srm-amqp-credits-bug.git

**Steps**
1. mvn quarkus:dev
2. Watch the output for these lines `DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16222: Retrieved credits for channel testX: 1000`
3. There should be 3 of them:  `test1`, `test2`, and `test3`.  Most of the time you will only see a subset of those acquire credits.

**Output from an error scenario**
Credits were obtained for test2 and test3.  Not for test1
```
2022-03-11 09:34:06,595 FINE  [org.apa.qpi.pro.eng.imp.SaslImpl] (vert.x-eventloop-thread-0) Handled outcome: SaslImpl [_outcome=PN_SASL_OK, state=PN_SASL_PASS, done=true, role=CLIENT]
2022-03-11 09:34:06,600 FINE  [org.apa.qpi.pro.eng.imp.SaslImpl] (vert.x-eventloop-thread-0) Handled outcome: SaslImpl [_outcome=PN_SASL_OK, state=PN_SASL_PASS, done=true, role=CLIENT]
2022-03-11 09:34:06,601 FINE  [org.apa.qpi.pro.eng.imp.SaslImpl] (vert.x-eventloop-thread-0) Handled outcome: SaslImpl [_outcome=PN_SASL_OK, state=PN_SASL_PASS, done=true, role=CLIENT]
2022-03-11 09:34:06,612 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16213: Connection with AMQP broker established
2022-03-11 09:34:06,619 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16213: Connection with AMQP broker established
2022-03-11 09:34:06,623 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16213: Connection with AMQP broker established
2022-03-11 09:34:06,640 DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16222: Retrieved credits for channel `test3`: 1000
2022-03-11 09:34:06,641 DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16222: Retrieved credits for channel `test2`: 1000
2022-03-11 09:34:12,022 ERROR [io.qua.sch.run.SimpleScheduler] (executor-thread-0) Error occured while executing task for trigger IntervalTrigger [id=1_com.alexlitovsky.bugs.amqp.MessageSender_ScheduledInvoker_sendMessage_28ac1eed06c7507f1cfe170b7c9ab14464f2f6dc, interval=60000]: java.lang.RuntimeException: Timeout sending to emitter1
	at com.alexlitovsky.bugs.amqp.MessageSender.sendMessage(MessageSender.java:46)
	at com.alexlitovsky.bugs.amqp.MessageSender.sendMessage(MessageSender.java:36)
	at com.alexlitovsky.bugs.amqp.MessageSender_Subclass.sendMessage$$superforward1(Unknown Source)
	at com.alexlitovsky.bugs.amqp.MessageSender_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.alexlitovsky.bugs.amqp.MessageSender_Subclass.sendMessage(Unknown Source)
	at com.alexlitovsky.bugs.amqp.MessageSender_ClientProxy.sendMessage(Unknown Source)
	at com.alexlitovsky.bugs.amqp.MessageSender_ScheduledInvoker_sendMessage_28ac1eed06c7507f1cfe170b7c9ab14464f2f6dc.invokeBean(Unknown Source)
	at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
	at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.run(SimpleScheduler.java:274)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:548)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at com.alexlitovsky.bugs.amqp.MessageSender.sendMessage(MessageSender.java:43)
	... 22 more
```

**Comment by cescoffier** [comment]
It may come from the "client sharing" (it shares the same client). I will have a look.

**Comment by cescoffier** [comment]
I just tried a few times using quarkus:dev, and it worked every single time. What's your java version? Are you running quarkus:dev or from a jar file.

**Comment by alexlitovsky** [comment]
```
openjdk version "11.0.14" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu11.54+23-CA (build 11.0.14+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.54+23-CA (build 11.0.14+9-LTS, mixed mode)
```
It fails for me almost consistently, though for different channels

**Comment by alexlitovsky** [comment]
Also just tried it from multiple computers and multiple OS's (Mac and Windows).  Able to reproduce almost consistently.

**Comment by alexlitovsky** [comment]
@cescoffier It seems to be caused by the latency of the broker and the application.
In my scenario, the broker was located in the same Azure region as I am.
When I moved the broker to Azure's "Central France" location, it works every time.

Basically it works when the broker is far way.  Doesn't work when the broker is close.

I checked in the "Central France" broker coordinates into my reproducer.

**Comment by cescoffier** [comment]
Hum, still the same result for me:
```
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-03-11 19:19:35,855 INFO  [io.sma.rea.mes.amqp] (Quarkus Main Thread) SRMSG16201: AMQP broker configured to fss-alex-test3.servicebus.windows.net:5671 for channel test2
2022-03-11 19:19:35,856 INFO  [io.sma.rea.mes.amqp] (Quarkus Main Thread) SRMSG16201: AMQP broker configured to fss-alex-test3.servicebus.windows.net:5671 for channel test3
2022-03-11 19:19:35,857 INFO  [io.sma.rea.mes.amqp] (Quarkus Main Thread) SRMSG16201: AMQP broker configured to fss-alex-test3.servicebus.windows.net:5671 for channel test1
2022-03-11 19:19:35,858 INFO  [io.sma.rea.mes.amqp] (Quarkus Main Thread) SRMSG16212: Establishing connection with AMQP broker
2022-03-11 19:19:35,859 INFO  [io.sma.rea.mes.amqp] (Quarkus Main Thread) SRMSG16212: Establishing connection with AMQP broker
2022-03-11 19:19:35,859 INFO  [io.sma.rea.mes.amqp] (Quarkus Main Thread) SRMSG16212: Establishing connection with AMQP broker
2022-03-11 19:19:35,863 INFO  [io.quarkus] (Quarkus Main Thread) srm-amqp-credits-bug TRUNK-SNAPSHOT on JVM (powered by Quarkus 2.7.4.Final) started in 0.117s.
2022-03-11 19:19:35,863 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2022-03-11 19:19:35,863 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, scheduler, smallrye-context-propagation, smallrye-reactive-messaging, smallrye-reactive-messaging-amqp, vertx]
2022-03-11 19:19:35,863 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Aesh InputStream Reader) Live reload total time: 0.125s
2022-03-11 19:19:35,971 FINE  [org.apa.qpi.pro.eng.imp.SaslImpl] (vert.x-eventloop-thread-7) Handled outcome: SaslImpl [_outcome=PN_SASL_OK, state=PN_SASL_PASS, done=true, role=CLIENT]
2022-03-11 19:19:35,975 FINE  [org.apa.qpi.pro.eng.imp.SaslImpl] (vert.x-eventloop-thread-7) Handled outcome: SaslImpl [_outcome=PN_SASL_OK, state=PN_SASL_PASS, done=true, role=CLIENT]
2022-03-11 19:19:35,989 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-7) SRMSG16213: Connection with AMQP broker established
2022-03-11 19:19:35,990 FINE  [org.apa.qpi.pro.eng.imp.SaslImpl] (vert.x-eventloop-thread-7) Handled outcome: SaslImpl [_outcome=PN_SASL_OK, state=PN_SASL_PASS, done=true, role=CLIENT]
2022-03-11 19:19:35,992 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-7) SRMSG16213: Connection with AMQP broker established
2022-03-11 19:19:36,007 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-7) SRMSG16213: Connection with AMQP broker established
2022-03-11 19:19:36,009 DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-7) SRMSG16222: Retrieved credits for channel `test3`: 1000
2022-03-11 19:19:36,012 DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-7) SRMSG16222: Retrieved credits for channel `test1`: 1000
2022-03-11 19:19:36,027 DEBUG [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-7) SRMSG16222: Retrieved credits for channel `test2`: 1000
2022-03-11 19:19:37,656 INFO  [io.quarkus] (Shutdown thread) srm-amqp-credits-bug stopped in 0.005s
```

I launched it 20 times, it always got the credits.

**Comment by alexlitovsky** [comment]
I created a VM co-located in Azure with the broker.  Will send you the VM info and exact steps by email.
I am able to reproduce it there consistently.

It's definitely a race condition:
2 cores:  could not reproduce
4 cores:  50/50
8 cores:  consistently reproducible

**Comment by cescoffier** [comment]
@alexlitovsky tha is, send me the details to clement@redhat.com

**Comment by cescoffier** [comment]
Thanks! I've found the bug.

Working on a fix.
The problem is a race when retrieving the credits. If the initial credits are not retrieved "in time", it just does nothing to retrieve more. Now, it will ask for more credits. 

Note that the emitters will still need to be protected with:

```
if (emitter.hasRequests()) {
			try {
				LOGGER.info("sending message to " + channelName + "...");
				emitter.send("Hello world").toCompletableFuture().get(5, TimeUnit.SECONDS);
				LOGGER.info("sent message to " + channelName);
			} catch (InterruptedException | ExecutionException | TimeoutException e) {
				throw new RuntimeException("Timeout sending to " + channelName, e);
			}
		} else {
			System.out.println("No credit for " + channelName);
		}
```

**Comment by cescoffier** [comment]
Here is the PR fixing it: https://github.com/smallrye/smallrye-reactive-messaging/pull/1668.

**Comment by alexlitovsky** [comment]
@cescoffier Is there a way to block until credits have been retrieved for a channel?  I don't think wrapping in an `if emitter.hasRequests()` helps us much.  Ultimately the messaging subsystem is not ready to be used until credits have been obtained.

**Comment by cescoffier** [comment]
hasRequests should be used almost every time you use an emitter. You cannot safely 'send' to a reactive world without checking if you have requests.

You can wait and retry until you have requests, but be sure you are on a thread you can block.

Note that the issue is not only happening on startup. It can happen when you are running out of credits (but that path was already covered).

**Comment by cescoffier** [comment]
The messaging system is ready, it just does not have the capacity. It got the first credits, they were 0. But the connection is established and the sender opened.
