### ISSUE TITLE
Exception when using constructor injection instead of field injection

### ISSUE THREAD

**Issue by grudid** [smallrye/smallrye-reactive-messaging#1967]
Hello,

i'm using version 4.0.0 of SmallRye Reactive Messaging with Kafka. I'm getting an IllegalArgumentException "object is not an instance of declaring class" when using constructor injection in my bean. If i use field injection the bean works as expected.
Is this a restriction of SmallRye Reactive Messaging or am i doing something wrong here?

Example code:

```
// doesn't work
@ApplicationScoped
public class Bar implements IBar {
	@Inject
	public Bar(Foo foo) { }

	@Incoming("user-in")
	public void processMessage(String message) { }
}

// works
@ApplicationScoped
public class Bar implements IBar {
	@Inject
	private Foo foo;

	@Incoming("user-in")
	public void processMessage(String message) { }
}

```

The stack trace looks as follows.

```
2022-11-03T10:02:10,895 [vert.x-eventloop-thread-0] ERROR io.sma.rea.mes.kafka - SRMSG18203: A message sent to channel `user-in` has been nacked, fail-stop
2022-11-03T10:02:10,910 [vert.x-eventloop-thread-0] ERROR sma.rea.mes.provider - SRMSG00201: Error caught while processing a message in method com.test.Bar#processMessage
io.smallrye.reactive.messaging.providers.ProcessingException: SRMSG00103: Exception thrown when calling the method com.test.Bar#processMessage
	at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$initialize$0(AbstractMediator.java:90) ~[smallrye-reactive-messaging-provider-4.0.0.jar:?]
	at io.smallrye.reactive.messaging.providers.AbstractMediator.invoke(AbstractMediator.java:104) ~[smallrye-reactive-messaging-provider-4.0.0.jar:?]
	at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeOnMessageContext$1(AbstractMediator.java:112) ~[smallrye-reactive-messaging-provider-4.0.0.jar:?]
	at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$0(LocalContextMetadata.java:34) ~[smallrye-reactive-messaging-provider-4.0.0.jar:?]
	at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$1(LocalContextMetadata.java:53) ~[smallrye-reactive-messaging-provider-4.0.0.jar:?]
	at io.smallrye.reactive.messaging.providers.helpers.VertxContext.runOnContext(VertxContext.java:24) ~[smallrye-reactive-messaging-provider-4.0.0.jar:?]
	at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$2(LocalContextMetadata.java:51) ~[smallrye-reactive-messaging-provider-4.0.0.jar:?]
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.request(UniToMultiPublisher.java:74) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onSubscribe(MultiFlatMapOp.java:601) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher.subscribe(UniToMultiPublisher.java:26) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:163) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:193) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.operators.multi.MultiOnItemInvoke$MultiOnItemInvokeProcessor.onItem(MultiOnItemInvoke.java:41) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.operators.multi.MultiOnItemInvoke$MultiOnItemInvokeProcessor.onItem(MultiOnItemInvoke.java:41) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:100) ~[mutiny-1.7.0.jar:?]
	at io.smallrye.reactive.messaging.providers.locals.ContextDecorator$ContextMulti$ContextProcessor.lambda$onItem$1(ContextDecorator.java:84) ~[smallrye-reactive-messaging-provider-4.0.0.jar:?]
	at io.smallrye.reactive.messaging.providers.helpers.VertxContext.lambda$runOnContext$0(VertxContext.java:26) ~[smallrye-reactive-messaging-provider-4.0.0.jar:?]
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264) ~[vertx-core-4.3.3.jar:4.3.3]
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246) ~[vertx-core-4.3.3.jar:4.3.3]
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43) ~[vertx-core-4.3.3.jar:4.3.3]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:202) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:100) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$initialize$0(AbstractMediator.java:88) ~[smallrye-reactive-messaging-provider-4.0.0.jar:?]
	... 36 more
```

My environment:
- OpenJDK-18.0.2.1
- JakartaEE 9.1.0
- OpenLiberty 22.0.0.11 on Windows 11

Thanks for your help.

**Comment by cescoffier** [comment]
Can you provide the CDI implementation and the version of SmallRye Reactive Messaging? 

Looks very outdated from the stack trace.

**Comment by cescoffier** [comment]
Seeing the Local metadata support, so not so outdated.

**Comment by ozangunalp** [comment]
My trials of setting up an OpenLiberty app using Smallrye Reactive Messaging have been unsuccessful. If you have a reproducer app I can take a look. Otherwise, we should address the question to the OpenLiberty team.

**Comment by cescoffier** [comment]
As @ozangunalp said, please provide a reproducer. However, it would be best if you ping the OpenLiberty team. Object creation uses the CDI container. The returned "proxy" (because most of the time it's a proxy) should implement the class and so provides the same methods.  

Maybe try to use `@Singleton` instead of `@ApplicationScoped`.

**Comment by grudid** [comment]
Thanks for the quick reply and sorry for my late answer. I have been quite busy the last few days. 
I pushed a working example at [GitHub](https://github.com/grudid/jee-reactive-messaging-sample). I hope this sheds some light on the situation.

@cescoffier Thanks for the hint about using `@Singleton`. I tried it out and it seems to work fine. But [Weld Documentation chapter 5.4](https://docs.jboss.org/weld/reference/5.0.0.Final/en-US/html_single/#_the_singleton_pseudo_scope) suggests to use `@ApplicationScope` instead of `@Singleton`. In my case serialization doesn't matter, so i can go that way.

**Comment by ozangunalp** [comment]
@grudid thanks for the reproducer, I can indeed run and reproduce the issue. 

It has to do with how managed bean proxies are handled by the container. By the CDI spec you need a no args constructor for your proxied managed bean (e.g `@ApplicationScoped`) – when you declare a constructor injection you need to create a no args constructor explicitly. Weld seems to relax this requirement : https://docs.jboss.org/weld/reference/5.0.0.Final/en-US/html_single/#relaxedConstruction. I don't know what the OpenLiberty uses as cdi implementation, but if you add a no args constructor for `Bar` class it'll work as intended.

**Comment by cescoffier** [comment]
Ah yes, Quarkus automatically adds such a constructor.

**Comment by grudid** [comment]
Hi, thanks for the clarification. I didn't knew about that fact in CDI.
