### ISSUE TITLE
NoSuchFileException exception when using Apache Camel connector and Camel file component

### ISSUE THREAD

**Issue by bgoetzmann** [smallrye/smallrye-reactive-messaging#2166]
Hello,

I have a strange behavior with my Quarkus application (v. 2.16.7.Final) using Smallrye Reactive Messaging with Apache Camel connector and Camel file component.
The application is very simple, with this ApplicationScoped component : 

```java
@ApplicationScoped
public class CamelReactive {

    @Incoming("camel")
    @Outgoing("stream-text")
    public Multi<String> consume(GenericFile<File> genfile) throws IOException {
        File file = genfile.getFile();
        List<String> content = Files.readAllLines(file.toPath());
        return Multi.createFrom().iterable(content);
    }

    @Incoming("stream-text")
    public void handle(String text) {
        System.out.println(text);
    }
}
``` 

The content of the `application.properties` is as follow:

```
mp.messaging.incoming.camel.connector=smallrye-camel
mp.messaging.incoming.camel.endpoint-uri=file:///temp/camel1?fileName=input.txt&delete=true
```

When I put a file `input.txt` the first time in `C:\temp\camel1` (I'm under Windows 11), each line of the content is displayed in the console, but the **second time**, I get this exception : 

```
2023-05-23 22:05:14,187 ERROR [io.sma.rea.mes.provider] (pool-1-thread-1) SRMSG00201: Error caught while processing a message in method com.odelia.mp.reactive.messaging.CamelReactive#handle: java.nio.file.NoSuchFileException: C:\temp\camel1\input.txt
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
...
```

Is there something obvious that I missed?

Thanks!

Here the source code of the project:
[mp-reactive-messaging1.zip](https://github.com/smallrye/smallrye-reactive-messaging/files/11548094/mp-reactive-messaging1.zip)

**Comment by cescoffier** [comment]
I'm not sure what causes this. @davsclaus maybe you have an idea?

**Comment by cescoffier** [comment]
Maybe it's because of the `delete=true` which delete the file once read.

**Comment by bgoetzmann** [comment]
Hello @cescoffier,

The behaviour is the same if I remove `delete=true`.
In a similar project, I use the `CamelReactiveStreamsService` service instead, using its `from("file://...")` method for the stream creation, and it works well.
I'm writing an article on it (with a combination with SSE), and I'll share soon the code source. However, I would have liked a working project with what MP Reactive Messaging allows for configuration.

PS: thank you for your great book "Reactive Systems in Java"!
