### ISSUE TITLE
SRMSG16215: Unable to connect to the broker when trying to connect to Amazon MQ (ActiveMQ)

### ISSUE THREAD

**Issue by syr** [smallrye/smallrye-reactive-messaging#2202]
Trying to connect to Amazon MQ via public domain name or IP fails.

Log gets filled with 
```
2023-06-20 22:01:46,539 ERROR [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16215: Unable to connect to the broker, retry will be attempted: io.vertx.core.VertxException: Disconnected
	at io.vertx.proton.impl.ProtonClientImpl.lambda$null$0(ProtonClientImpl.java:81)
	at io.vertx.proton.impl.ProtonConnectionImpl.fireDisconnect(ProtonConnectionImpl.java:381)
	at io.vertx.proton.impl.ProtonTransport.handleSocketEnd(ProtonTransport.java:95)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:95)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:239)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:129)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
	at io.vertx.core.net.impl.NetSocketImpl.handleClosed(NetSocketImpl.java:384)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Reproducer (just start up amqp-quickstart-producer with env vars `AMQP_PORT=5671;AMQP_USERNAME=****;AMQP_HOST=******;AMQP_PASSWORD=***********`)

https://github.com/syr/quarkus-resteasy-postgres/tree/amqp_test

Broker engine: ActiveMQ
Broker engine version: 5.17.2

Inbound rules of Amazon MQ's security group properly configured to allow incoming requests and env var keys and values are correct/double checked.

Am I doing which basically cannot work?

Maybe something special to know about host property to be set?

I set env vars
```
AMQP_HOST=b-<UUID>-1.mq.us-east-2.amazonaws.com
AMQP_PORT=5671
```

Endpoints
OpenWire
ssl://b-<UUID>-1.mq.us-east-2.amazonaws.com:61617
AMQP
amqp+ssl://b-<UUID>-1.mq.us-east-2.amazonaws.com:5671
STOMP
stomp+ssl://b-<UUID>-1.mq.us-east-2.amazonaws.com:61614
MQTT
mqtt+ssl://b-<UUID>-1.mq.us-east-2.amazonaws.com:8883
WSS
wss://b-<UUID>-1.mq.us-east-2.amazonaws.com:61619

**Comment by cescoffier** [comment]
Unfortunately, I could not create an AWS MQ instance for the last week (some weird cors issue).

Also, you need to enable SSL.

**Comment by syr** [comment]
@cescoffier thanks for that hint. You are right, only  `amqp-use-ssl=true` was missing, then everything worked. 

FYI I was only creating the broker with config
Broker instance type
Info
mq.t3.micro
Deployment mode
Info
Single-instance broker
Storage type
Info
Amazon Elastic File System
Broker engine
Info
ActiveMQ
Broker engine version
5.17.3

and added an inbound rule in the associated security group to allow all TCP from my public client's IP.
