### ISSUE TITLE
Kafka - ack chain breaks when trying to publish to a compacted topic without a key

### ISSUE THREAD

**Issue by chrisnad** [smallrye/smallrye-reactive-messaging#2270]
When trying to push an outgoing message with null key to a compacted topic, smallrye will retry in a loop for ~60-120 seconds before nacking and returning an InvalidRecordException. 

The problem arises when we have an incoming channel with commit-strategy:throttled. In the case where we unsuccessfully retry for more than a minute to ack the outgoing message, when it finally returns (with a nack), trying to ack the incoming message now will fail because smallrye has lost track of it. This breaks the ack chain and leads to the application crashing.

The simplest solution was to increase throttled.unprocessed-record-max-age.ms to be greated than 120 seconds (default is 60 seconds)

Is this the intended behaviour? if so, is there a way to make it fail immediately?

Build/Runtime: java 20

**Comment by cescoffier** [comment]
Both timeout should be the same by default. So, one of the default is wrong.

**Comment by chrisnad** [comment]
Any idea what the parameter name for the InvalidRecordException retry timeout is? I do not expressly set such a value so I assume if there is such a parameter then the default value is used. That being said that value is not 60 seconds and tests show an undeterministic timeout, here for example it's 1 minute 43 seconds but it could be anywhere from 1:30 to 2 minutes

```
2023-08-23 12:12:00,136 ERROR [io.sma.rea.mes.kafka] (kafka-producer-network-thread | kafka-producer-out) SRMSG18206: Unable to write to Kafka from channel out (topic: my_topic): org.apache.kafka.common.InvalidRecordException: Compacted topic cannot accept message without key in topic partition my_topic-1.

2023-08-23 12:12:02,945 ERROR [io.sma.rea.mes.kafka] (kafka-producer-network-thread | kafka-producer-out) SRMSG18206: Unable to write to Kafka from channel out (topic: my_topic): org.apache.kafka.common.InvalidRecordException: Compacted topic cannot accept message without key in topic partition my_topic-1.

2023-08-23 12:12:05,161 ERROR [io.sma.rea.mes.kafka] (kafka-producer-network-thread | kafka-producer-out) SRMSG18206: Unable to write to Kafka from channel out (topic: my_topic): org.apache.kafka.common.InvalidRecordException: Compacted topic cannot accept message without key in topic partition my_topic-1.

2023-08-23 12:12:16,293 ERROR [io.sma.rea.mes.kafka] (kafka-producer-network-thread | kafka-producer-out) SRMSG18206: Unable to write to Kafka from channel out (topic: my_topic): org.apache.kafka.common.InvalidRecordException: Compacted topic cannot accept message without key in topic partition my_topic-1.

2023-08-23 12:12:31,415 ERROR [io.sma.rea.mes.kafka] (kafka-producer-network-thread | kafka-producer-out) SRMSG18206: Unable to write to Kafka from channel out (topic: my_topic): org.apache.kafka.common.InvalidRecordException: Compacted topic cannot accept message without key in topic partition my_topic-1.

2023-08-23 12:12:43,878 ERROR [io.sma.rea.mes.kafka] (kafka-producer-network-thread | kafka-producer-out) SRMSG18206: Unable to write to Kafka from channel out (topic: my_topic): org.apache.kafka.common.InvalidRecordException: Compacted topic cannot accept message without key in topic partition my_topic-1.

2023-08-23 12:12:58,603 ERROR [io.sma.rea.mes.kafka] (kafka-producer-network-thread | kafka-producer-out) SRMSG18206: Unable to write to Kafka from channel out (topic: my_topic): org.apache.kafka.common.InvalidRecordException: Compacted topic cannot accept message without key in topic partition my_topic-1.

2023-08-23 12:13:12,208 ERROR [io.sma.rea.mes.kafka] (kafka-producer-network-thread | kafka-producer-out) SRMSG18206: Unable to write to Kafka from channel out (topic: my_topic): org.apache.kafka.common.InvalidRecordException: Compacted topic cannot accept message without key in topic partition my_topic-1.

2023-08-23 12:13:27,901 ERROR [io.sma.rea.mes.kafka] (kafka-producer-network-thread | kafka-producer-out) SRMSG18206: Unable to write to Kafka from channel out (topic: my_topic): org.apache.kafka.common.InvalidRecordException: Compacted topic cannot accept message without key in topic partition my_topic-1.

2023-08-23 12:13:47,548 ERROR [io.sma.rea.mes.kafka] (kafka-producer-network-thread | kafka-producer-out) SRMSG18206: Unable to write to Kafka from channel out (topic: my_topic): org.apache.kafka.common.InvalidRecordException: Compacted topic cannot accept message without key in topic partition my_topic-1.

2023-08-23 12:13:47,548 ERROR [io.sma.rea.mes.kafka] (kafka-producer-network-thread | kafka-producer-out) SRMSG18212: Message org.eclipse.microprofile.reactive.messaging.Message$8@13f92fbc was not sent to Kafka topic 'my_topic' - nacking message: java.lang.IllegalStateException: Retries exhausted : 10 attempts against 1692792840593/1692792840134 expiration
        at io.smallrye.mutiny.helpers.ExponentialBackoff.lambda$randomExponentialBackoffFunctionExpireAt$2(ExponentialBackoff.java:112)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.groups.MultiOnItem.lambda$transformToUni$6(MultiOnItem.java:267)
        at io.smallrye.mutiny.operators.multi.MultiConcatMapOp$ConcatMapMainSubscriber.onItem(MultiConcatMapOp.java:139)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.operators.multi.processors.UnicastProcessor.drainWithDownstream(UnicastProcessor.java:107)
        at io.smallrye.mutiny.operators.multi.processors.UnicastProcessor.drain(UnicastProcessor.java:138)
        at io.smallrye.mutiny.operators.multi.processors.UnicastProcessor.onNext(UnicastProcessor.java:204)
        at io.smallrye.mutiny.operators.multi.processors.SerializedProcessor.onNext(SerializedProcessor.java:104)
        at io.smallrye.mutiny.subscription.SerializedSubscriber.onItem(SerializedSubscriber.java:74)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.operators.multi.MultiRetryWhenOp$RetryWhenOperator.onFailure(MultiRetryWhenOp.java:127)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onError(MultiSubscriber.java:73)
        at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onFailure(UniToMultiPublisher.java:102)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
        at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.fail(DefaultUniEmitter.java:53)
        at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.lambda$send$3(ReactiveKafkaProducer.java:172)
        at org.apache.kafka.clients.producer.KafkaProducer$AppendCallbacks.onCompletion(KafkaProducer.java:1505)
        at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:273)
        at org.apache.kafka.clients.producer.internals.ProducerBatch.done(ProducerBatch.java:234)
        at org.apache.kafka.clients.producer.internals.ProducerBatch.completeExceptionally(ProducerBatch.java:198)
        at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:766)
        at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:742)
        at org.apache.kafka.clients.producer.internals.Sender.completeBatch(Sender.java:642)
        at org.apache.kafka.clients.producer.internals.Sender.lambda$null$1(Sender.java:583)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.apache.kafka.clients.producer.internals.Sender.lambda$handleProduceResponse$2(Sender.java:570)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.apache.kafka.clients.producer.internals.Sender.handleProduceResponse(Sender.java:570)
        at org.apache.kafka.clients.producer.internals.Sender.lambda$sendProduceRequest$5(Sender.java:844)
        at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109)
        at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:583)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:575)
        at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:328)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
        at java.base/java.lang.Thread.run(Thread.java:1623)
        Caused by: org.apache.kafka.common.InvalidRecordException: Compacted topic cannot accept message without key in topic partition my_topic-1.
```

**Comment by ozangunalp** [comment]
I agree that on this setting we should have the `throttled.unprocessed-record-max-age.ms` value set to at least the default value of `delivery.timeout.ms`, which is `120000`.
