### ISSUE TITLE
RabbitMQ - Override a property from an ENV VAR crash the boot.

### ISSUE THREAD

**Issue by lerminou** [smallrye/smallrye-reactive-messaging#2462]
I have a quarkus smallrye application with rabbitMQ
```
io.smallrye.reactive:smallrye-reactive-messaging-provider::jar:4.5.0
io.smallrye.reactive:smallrye-reactive-messaging-rabbitmq::jar:4.5.0
```

When setting all properties in the application.properties, everything is OK
```
# Input message consumer
mp.messaging.incoming.oversized-file-in.connector=smallrye-rabbitmq
mp.messaging.incoming.oversized-file-in.virtual-host=/
mp.messaging.incoming.oversized-file-in.routing-keys=message.oversized-file.in

mp.messaging.incoming.oversized-file-in.queue.declare=true
mp.messaging.incoming.oversized-file-in.queue.name=ftp-oversized-file-in-queue
mp.messaging.incoming.oversized-file-in.queue.durable=true
mp.messaging.incoming.oversized-file-in.queue.auto-delete=false
```

I'm trying to override the virtualHost from an env var directly in my kubernetes pod.

```
      containers:
      - env:
        - name: MP_MESSAGING_INCOMING_oversized-file-in_VIRTUAL_HOST
          value: "testqa"
```

After that, the application is not booting anymore
I tried multiples format for the env var (full caps, no caps, hyphen, dots, )
I also tried to set the connector in another env var but no effect
```
        - name: MP_MESSAGING_INCOMING_oversized-file-in_CONNECTOR
          value: "smallrye-rabbitmq"
```
error:
```
Invalid channel configuration -  the `connector` attribute must be set for channel `oversized-file-in`
````
stacktrace:
```
{"timestamp":"2024-01-26T10:27:39.836Z","sequence":303,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.runtime.Application",
"level":"ERROR","message":"Failed to start application (with profile [prod])","threadName":"main","threadId":1,"mdc":{},"ndc":"","processName":"quarkus-run.jar","processId":1,
"stackTrace":"java.lang.IllegalArgumentException: SRMSG00071: Invalid channel configuration -  the `connector` attribute must be set for channel `oversized-file-in`
  at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.lambda$new$0(ConnectorConfig.java:50)
  at java.base/java.util.Optional.orElseThrow(Optional.java:403)
  at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.lambda$new$1(ConnectorConfig.java:50)
  at java.base/java.util.Optional.orElseGet(Optional.java:364)
  at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.<init>(ConnectorConfig.java:49)
  at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.lambda$extractConfigurationFor$0(ConfiguredChannelFactory.java:86)
  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.extractConfigurationFor(ConfiguredChannelFactory.java:75)
  at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:101)
  at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory_ClientProxy.initialize(Unknown Source)
  at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
  at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
  at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
  at io.smallrye.reactive.messaging.providers.extension.MediatorManager.start(MediatorManager.java:206)
  at io.smallrye.reactive.messaging.providers.extension.MediatorManager_ClientProxy.start(Unknown Source)
  at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:52)
  at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_68e7b57eb97cb75d597c5b816682366e888d0d9b.notify(Unknown Source)
  at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
  at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
  at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
  at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
  at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
  at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
  at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
  at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
  at io.quarkus.runtime.Application.start(Application.java:101)
  at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
  at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
  at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
  at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
  at io.quarkus.runner.GeneratedMain.main(Unknown Source)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
  at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
"}
```

I found some old tickets related to the management of env vars
https://github.com/smallrye/smallrye-reactive-messaging/issues/419
https://github.com/smallrye/smallrye-reactive-messaging/issues/1264
https://github.com/smallrye/smallrye-reactive-messaging/issues/1907

**Comment by cescoffier** [comment]
`MP_MESSAGING_INCOMING_oversized-file-in_VIRTUAL_HOST` is not a valid env property. It needs to be:
`MP_MESSAGING_INCOMING_OVERSIZED_FILE_IN_VIRTUAL_HOST`.

Env variable have rules: lower cases and - are not legal. Docker compose accept them, but it breaks (or bends) the rule.

**Comment by lerminou** [comment]
HI @cescoffier , yes I tried to set this format too but it doesn't work with the same exception

**Comment by lerminou** [comment]
Hi cescoffier, I tried to set the whole string in uppercase, but I tried again, by copying your value and it works this time , Maybe I had a typo ...

Sorry for the inconvenience.
