### ISSUE TITLE
NullPointerException when a non recoverable KafkaException is thrown from the Kafka producer

### ISSUE THREAD

**Issue by vietk** [smallrye/smallrye-reactive-messaging#2486]
Hello

I wanted to test the [ProducerInterceptor](https://smallrye.io/smallrye-reactive-messaging/latest/kafka/writing-kafka-records/#producer-interceptors) feature. 
When I tried a message that exceeds the topic limit (generate a KafkaException) I have the following error
```shell
22:51:32,308 TRACE [io.smallrye.reactive.messaging.kafka] - SRMSG18275: Error caught in producer interceptor `onAcknowledge` for channel output-record
java.lang.NullPointerException
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.getRecordMetadataForFailure(ReactiveKafkaProducer.java:360)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.interceptOnAcknowledge(ReactiveKafkaProducer.java:351)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.lambda$send$3(ReactiveKafkaProducer.java:165)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:1062)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:947)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.lambda$send$4(ReactiveKafkaProducer.java:164)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:47)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.forwardTo(UniMemoizeOp.java:123)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.subscribe(UniMemoizeOp.java:67)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)


```
This prevent any ProducerInterceptor  onAcknowledge method to be called because the connector reports an error before.

Regards
Kevin

**Comment by ozangunalp** [comment]
Closed by #2487
