### ISSUE TITLE
`BlockingWithoutExecutionHolderTest` is flaky

### ISSUE THREAD

**Issue by ozangunalp** [smallrye/smallrye-reactive-messaging#2529]
It started failing on main : https://github.com/smallrye/smallrye-reactive-messaging/actions/runs/8261994956/job/22600445034

```
Suppressed: io.smallrye.reactive.messaging.providers.wiring.TooManyDownstreamCandidatesException: 'PublisherMethod{method:'io.smallrye.reactive.messaging.blocking.BlockingWithoutExecutionHolderTest$MyApplication#produce', outgoing:'a'}' supports a single downstream consumer, but found 2: [SubscriberMethod{method:'io.smallrye.reactive.messaging.blocking.BlockingWithoutExecutionHolderTest$MyApplication#consume', incoming:'a'}, OutgoingConnector{channel:'A', attribute:'mp.messaging.outgoing.A'}]. You may want to enable broadcast using '@Broadcast' on the method PublisherMethod{method:'io.smallrye.reactive.messaging.blocking.BlockingWithoutExecutionHolderTest$MyApplication#produce', outgoing:'a'}.
		at io.smallrye.reactive.messaging.providers.wiring.Wiring$PublisherMediatorComponent.validate(Wiring.java:663)
		at io.smallrye.reactive.messaging.providers.wiring.Graph.<init>(Graph.java:67)
		at io.smallrye.reactive.messaging.providers.wiring.Wiring.resolve(Wiring.java:211)
		at io.smallrye.reactive.messaging.providers.wiring.Wiring$Proxy$_$$_WeldClientProxy.resolve(Unknown Source)
		at io.smallrye.reactive.messaging.providers.extension.MediatorManager.start(MediatorManager.java:253)
```

**Comment by ozangunalp** [comment]
It is probably due to a config not being cleaned properly.
