### ISSUE TITLE
How to write Integration Tests for Reactive Messaging Applications

### ISSUE THREAD

**Issue by Legion2** [smallrye/smallrye-reactive-messaging#365]
Currently there is no documentation about writing tests for messaging applications using the MicroProfile api.
Writing Unit tests is straightforward you can simply call the annotated method. But if you want to write Integration Tests you have to face multiple problems. You don't want to setup the middleware and all connected systems. You want to inject messages into channels and verify messages send to channels.

Summary:
For integration tests it should be possible to mock, stub and verify incoming and outgoing channels and messages. Stateful interactions with incoming and outgoing messages should be testable. Also the interaction of HTTP Resources using Emitters should be testable.

**Comment by vietk** [comment]
Agreeing with this comment however I saw that there's a new [InMemoryConnector](https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/connector/InMemoryConnector.java), that would allow you to verify sent to an outgoing sink (InMemorySink) and setup incoming messages (InMemorySource).

**Comment by Legion2** [comment]
Now i found [the documentation](https://github.com/smallrye/smallrye-reactive-messaging/blob/master/doc/testing.adoc) for the `InMemoryConnector`, but it does not provide a complete example. So it's not clear which testing framework, library and runtime should be used for the Test.

I tried the `InMemoryConnector` from `1.0.9-SNAPSHOT`(local build) with `junit-vintage-engine` (Junit 4) and the Arquillian Runner using the `arquillian-liberty-managed` container. I created the following test (simplified):
```
@RunWith(Arquillian.class)
public class SomeIntegrationTest {
	@Deployment(testable = true)
	public static WebArchive createDeployment() {
		// Import Maven runtime dependencies
		File[] files = Maven.resolver().loadPomFromFile("pom.xml").importRuntimeAndTestDependencies().resolve()
				.withTransitivity().asFile();
		WebArchive archive = ShrinkWrap.create(WebArchive.class, "some.war")
				.addPackages(true, "de.uni_stuttgart.tik.viplab").addAsLibraries(files)
				.addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml");
		return archive;
	}
	
	@Inject @Any
	private InMemoryConnector connector;

	@BeforeClass
	public static void setup() throws MalformedURLException, URISyntaxException {
		InMemoryConnector.switchChannelToInMemory("results", "solutions");
	}

	@AfterClass
	public static void revertMyChannels() {
		InMemoryConnector.clear();
	}

	@Test
	@RunAsClient
	public void testConnectionIsPossible() throws InterruptedException {
		TestWebSocket websocket = new TestWebSocket(webSocketUri);
		assertThat("WebSocket connection to " + webSocketUri, websocket.connectBlocking(1000, TimeUnit.MILLISECONDS));
	}
}
```
SUT:
```
@ApplicationScoped
public class ECSComputationService {

	@Inject
	@Channel("solutions")
	private Emitter<Object> solutions;
...
```

And get an DeploymentException when running the tests:
```
com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: No channel found for name: solutions, injection point: [BackedAnnotatedField] @Inject @Channel private de.uni_stuttgart.tik.viplab.websocket_api.ecs.ECSComputationService.solutions
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:55)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:550)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:347)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1266)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1114)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:889)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.weld.exceptions.DeploymentException: No channel found for name: solutions, injection point: [BackedAnnotatedField] @Inject @Channel private de.uni_stuttgart.tik.viplab.websocket_api.ecs.ECSComputationService.solutions
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:38)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:505)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
	at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:157)
	at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:448)
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
	... 13 more
Caused by: javax.enterprise.inject.spi.DeploymentException: No channel found for name: solutions, injection point: [BackedAnnotatedField] @Inject @Channel private de.uni_stuttgart.tik.viplab.websocket_api.ecs.ECSComputationService.solutions
	at io.smallrye.reactive.messaging.extension.ReactiveMessagingExtension.afterDeploymentValidation(ReactiveMessagingExtension.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
	... 19 more

```
I used https://openliberty.io/guides/arquillian-managed.html for the test setup.

**Comment by Legion2** [comment]
The problem is when using Arquillian the `@BeforeClass` is executed after the application is deployed. But the application deployment fails because there are no connectors configured by default. I solved that problem by adding `.addAsResource("META-INF/microprofile-config.properties")` to the `WebArchive` which contains the configuration for the in memory connectors:
```properties
mp.messaging.incoming.results.connector=smallrye-in-memory
mp.messaging.outgoing.solutions.connector=smallrye-in-memory
```

**Comment by aguibert** [comment]
hi @Legion2, just saw this issue. I've been developing a MicroProfile/JakartaEE testing library called MicroShed Testing, and in the latest version (0.8) I added support for testing an application using MP Reactive Messaging (specifically Kafka).

It accomplishes this using real docker containers (via Testcontainers) and works with many different runtimes (Quarkus, OpenLiberty, Wildfly, Payara)

here is the specific documentation on testing MP reactive messaging w/ Kafka:
https://microshed.org/microshed-testing/features/KafkaMessaging.html

Towards the bottom you will also find a link to a working example application you can try out:
https://github.com/MicroShed/microshed-testing/tree/master/sample-apps/kafka-app

HTH

**Comment by Legion2** [comment]
@aguibert Can I use your library without Testcontainer and stub the message channels directly in the MicroProfile applications. I don't want so heavy dependencies on external tools, like Testcontainer and Kafka.

**Comment by aguibert** [comment]
not really -- it's primarily meant to be used with Testcontainers. Right now it's a bit heavyweight but we are working on some features to be able to reuse containers across multiple local test runs so you don't need to wait for containers to start up each time, but you still get the true-to-production tests.

**Comment by Legion2** [comment]
New Integration Tests documentation can be found [here](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/testing/testing.html). But I have problems injecting the `InMemoryConnector` in a Quarkus Test quarkusio/quarkus#6427.

**Comment by cescoffier** [comment]
@Legion2 I just open a PR fixing it - #530 

* The jar needs an index (jandex)
* I've made the API more "Quarkus Test Resource friendly"
* The previous API could fail because of channel name validation (it's in the spec but was not implemented correctly - the enforcement was improved in 2.0)
