### ISSUE TITLE
NPE when broadcasting emitted messages to SSE

### ISSUE THREAD

**Issue by iocanel** [smallrye/smallrye-reactive-messaging#414]
The following example:

```java
  @Inject
  @Channel("issues")
  Emitter<Status> emitter;

  @Inject
  @Channel("issues-out")
  Publisher<Status> status;

  @Incoming("issues")
  @Outgoing("issues-out")
  @Broadcast
  public Status publish(Status status) {
     return status;
  }

   @GET
   @Path("/issues/status")
   @Produces(MediaType.SERVER_SENT_EVENTS)
   @SseElementType(MediaType.APPLICATION_JSON)
   public Publisher<Status> streamIssues() {
        return status;
    }

   @GET
   @Path("/issues/collect")
   public void collectIssues() {
        fetchIssues().stream()
                     .map(i -> { emitter.send(new Status(i); return i})
                     .forEach(i.persist());
    }
```

Results in:

```
Caused by: java.lang.NullPointerException: Processor must not be null
at java.util.Objects.requireNonNull(Objects.java:228)
at org.eclipse.microprofile.reactive.streams.operators.core.Stages$ProcessorStage.<init>(Stages.java:175)
at org.eclipse.microprofile.reactive.streams.operators.core.PublisherBuilderImpl.via(PublisherBuilderImpl.java:186)
at io.smallrye.reactive.messaging.ProcessorMediator.connectToUpstream(ProcessorMediator.java:31)
at io.smallrye.reactive.messaging.extension.MediatorManager.lambda$null$5(MediatorManager.java:210)
at java.util.Optional.ifPresent(Optional.java:159)
at io.smallrye.reactive.messaging.extension.MediatorManager.lambda$weaving$6(MediatorManager.java:209)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at io.smallrye.reactive.messaging.extension.MediatorManager.weaving(MediatorManager.java:204)
at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:188)
at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:100)
at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
... 14 more
```

**Comment by cescoffier** [comment]
Ok, it's tricky...

It's only happening in Quarkus, because of ArC. 

Before doing the "incoming/outgoing" resolution, Reactive Messaging creates an instance of the class. However, with ArC it fails because the `@Channel` is not yet resolved. 

To fix this we would need to change the resolution algorithm to:

1. Inject fake "channels" so the bean can be resolved
2. Once the resolution is completed, change the injected channel to the real one (and fail if it can't)

**Comment by cescoffier** [comment]
This issue is finally fixed with the new wiring algorithm.
