### ISSUE TITLE
question: kafka: This processor allows only a single Subscriber

### ISSUE THREAD

**Issue by nicolaemarasoiu** [smallrye/smallrye-reactive-messaging#552]
Hi, using quarkus, which i noticed is using your adaptor for kafka topic consumer,
Is there any possibility of allowing multiple consumers (broadcast)?
I realize that Flowable is back-pressurable, and Observable is the right type for broadcast, as hot data.
But Observable is not accepted on the http controller side.
From your side, would it be possible to work as a hot source? or maybe backpressured only by the fastest consumer, and be hot for the others?
Just for curiosity. The browser script can do refresh every second or so, and I keep the current state in memory, so a feature to be able to get updates on all http connections, and with the possibility of initiating new requests to get the current state kept in memory (via onNext(setInMem)) would be a solution for our need of realtime analytics.
Please let me know any context, concerns, and theoretical/practical limitations, thank you.
```
 ERROR [io.sma.rea.mes.kaf.imp.KafkaSource] (executor-thread-1) Unable to read a record from Kafka topic 'migrations_dailyy_counter': java.lang.IllegalStateException: This processor allows only a single Subscriber
        at io.smallrye.mutiny.vertx.MultiReadStream.subscribe(MultiReadStream.java:62)
        at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:37)
        at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:68)
        at io.smallrye.mutiny.operators.multi.MultiSignalConsumerOp.subscribe(MultiSignalConsumerOp.java:60)
        at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:48)
        at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:48)
        at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.lambda$subscribe$0(ContextPropagationMultiInterceptor.java:58)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.subscribe(ContextPropagationMultiInterceptor.java:58)
        at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:37)
        at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:68)
        at io.smallrye.mutiny.operators.multi.MultiSignalConsumerOp.subscribe(MultiSignalConsumerOp.java:60)
        at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:48)
        at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:48)
        at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.lambda$subscribe$0(ContextPropagationMultiInterceptor.java:58)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.subscribe(ContextPropagationMultiInterceptor.java:58)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)

```

**Comment by cescoffier** [comment]
You can use the `@Broadcast` annotation to transform the stream into a hot stream:

https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/advanced/broadcast.html

You can also use the Mutiny API directly to do so:
https://smallrye.io/smallrye-mutiny/#_how_do_i_create_hot_streams
