### ISSUE TITLE
Problem with "mvn test -Dtest=EventBusSinkTest" in smallrye-reactive-messaging-vertx-eventbus

### ISSUE THREAD

**Issue by hutchig** [smallrye/smallrye-reactive-messaging#568]
I can run through each individual test in EventBusSinkTest OK but in a batch run
I get 'too many open files'. The error is:
 
May 30, 2020 8:53:30 AM org.jboss.weld.environment.se.WeldContainer shutdown
INFO: WELD-ENV-002001: Weld SE container 59d5d3a7-de69-4e4b-a713-54ae9267b76c shut down
Exception in thread "vert.x-eventloop-thread-5" java.lang.NoClassDefFoundError: Could not initialize class sun.nio.ch.FileDispatcherImpl
	at java.base/sun.nio.ch.KQueueSelectorImpl.implClose(KQueueSelectorImpl.java:246)
	at java.base/sun.nio.ch.SelectorImpl.implCloseSelector(SelectorImpl.java:180)
	at java.base/java.nio.channels.spi.AbstractSelector.close(AbstractSelector.java:111)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.close(SelectedSelectionKeySetSelector.java:78)
	at io.netty.channel.nio.NioEventLoop.cleanup(NioEventLoop.java:585)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1036)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
Exception in thread "vert.x-eventloop-thread-2" java.lang.NoClassDefFoundError: Could not initialize class sun.nio.ch.FileDispatcherImpl
	at java.base/sun.nio.ch.KQueueSelectorImpl.implClose(KQueueSelectorImpl.java:246)
	at java.base/sun.nio.ch.SelectorImpl.implCloseSelector(SelectorImpl.java:180)
	at java.base/java.nio.channels.spi.AbstractSelector.close(AbstractSelector.java:111)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.close(SelectedSelectionKeySetSelector.java:78)
	at io.netty.channel.nio.NioEventLoop.cleanup(NioEventLoop.java:585)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1036)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
Exception in thread "vert.x-eventloop-thread-1" java.lang.NoClassDefFoundError: Could not initialize class sun.nio.ch.FileDispatcherImpl
	at java.base/sun.nio.ch.KQueueSelectorImpl.implClose(KQueueSelectorImpl.java:246)
	at java.base/sun.nio.ch.SelectorImpl.implCloseSelector(SelectorImpl.java:180)
	at java.base/java.nio.channels.spi.AbstractSelector.close(AbstractSelector.java:111)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.close(SelectedSelectionKeySetSelector.java:78)
	at io.netty.channel.nio.NioEventLoop.cleanup(NioEventLoop.java:585)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1036)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
Exception in thread "vert.x-eventloop-thread-0" java.lang.ExceptionInInitializerError
	at java.base/sun.nio.ch.KQueueSelectorImpl.implClose(KQueueSelectorImpl.java:246)
	at java.base/sun.nio.ch.SelectorImpl.implCloseSelector(SelectorImpl.java:180)
	at java.base/java.nio.channels.spi.AbstractSelector.close(AbstractSelector.java:111)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.close(SelectedSelectionKeySetSelector.java:78)
	at io.netty.channel.nio.NioEventLoop.cleanup(NioEventLoop.java:585)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1036)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.io.IOException: Too many open files
	at java.base/sun.nio.ch.FileDispatcherImpl.init(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.<clinit>(FileDispatcherImpl.java:38)
	... 9 more

commit 5cf72f6715786790fce6159235a9c8eb61b44499 (HEAD -> master, origin/master, origin/HEAD)
OSX and openjdk (hotspot) 13.0.2

$ java -version
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)

~/git/smallrye-reactive-messaging/smallrye-reactive-messaging-vertx-eventbus/target
$ sudo sysctl -w kern.maxfilesperproc=24576
Password:
kern.maxfilesperproc: 24576 -> 24576
~/git/smallrye-reactive-messaging/smallrye-reactive-messaging-vertx-eventbus/target
$ sudo sysctl -w kern.maxfiles=49152
kern.maxfiles: 49152 -> 49152
~/git/smallrye-reactive-messaging/smallrye-reactive-messaging-vertx-eventbus/target
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4000
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2784
virtual memory          (kbytes, -v) unlimited

Using the debugger and lsof > XXXRun  and stopping every few tests (not rigourous), I see
$ wc *Run
   12092  108758 1883670 2ndRun
   12917  115083 1982078 3ndRun
   13895  122585 2099052 4thRun

What seems to be growing in lsof is these:

< java      2024            hutchig 3988u   KQUEUE                                                   count=1, state=0x8
< java      2024            hutchig 3989      PIPE 0xda6ba1d852eabf33      16384                     ->0x305ef6a285a5d648
< java      2024            hutchig 3990      PIPE 0x305ef6a285a5d648      16384                     ->0xda6ba1d852eabf33

I will attach some more data files below.

**Comment by hutchig** [comment]
[lsof-output1.log](https://github.com/smallrye/smallrye-reactive-messaging/files/4705359/lsof-output1.log)
[lsof-output2.log](https://github.com/smallrye/smallrye-reactive-messaging/files/4705360/lsof-output2.log)

I am happy to do some more digging around to see if I can narrow it down more.

**Comment by hutchig** [comment]
Surefire reports dir:


[surefire-reports.zip](https://github.com/smallrye/smallrye-reactive-messaging/files/4705369/surefire-reports.zip)

**Comment by kenfinnigan** [comment]
Do you mean that you can run `mvn clean install` from the `smallrye-reactive-messaging-vertx-eventbus` directory and see this problem?

I just did that from the latest master and didn't have any warnings about open files

**Comment by hutchig** [comment]
Yes.

**Comment by kenfinnigan** [comment]
It's a cliche, but it sounds like it's an issue with your machine only.

**Comment by hutchig** [comment]
Could be, I have no evidence for the 'only' bit at the moment though.
[screen.log](https://github.com/smallrye/smallrye-reactive-messaging/files/4711646/screen.log)

**Comment by hutchig** [comment]
It is something set up in the @Before of the superclass not being cleaned up I think.

Here is my evidence/reasoning: 

If I edit EventBusSinkTest to remove all @Test annotations
then make @Test method that just calls testSendAndMultipleConsumers()
once, it works fine. 

If I duplicate that method (with a differentiating method name suffix)
I can only have 5 of those type of test methods reliably. 

I get the problem on the 6th one which fails reliably, reverting to 5 ..passes reliably. 
I can do this even with the 6th method body being blank!:

// 1 to 5 are here....
...
    //@Test     <---- toggle this to make 'mvn clean install' fail
    @SuppressWarnings("unchecked")
    public void testSendAndMultipleConsumersManyTimes6() {
        //  testSendAndMultipleConsumers();
    }

Then, if I have a single test calling testSendAndMultipleConsumers()
N times, I can call that method many many more times that is done above
times no problem - tried up to 14 times.

There is no @Before in either of the two failing testcases EventBusSource/Sink test
but they have a common superclass with

   @Before
    public void setup() {
        vertx = Vertx.vertx();
        usage = new EventBusUsage(vertx.eventBus().getDelegate());
    }

Maven seems to be running each test 10 times
("Tests run: 50, Failures: 0, Errors: 0, Skipped: 0")

So it works with 50 Vert.x's and EventBusUsage
being cycled using @Before and @After and fails for 60.

**Comment by cescoffier** [comment]
Working on a fix... the Vert.x instances are not closed (close() returns a `Uni`, and no one subscribes...)

**Comment by cescoffier** [comment]
See #6d79ef5aa7593083c2e8b0c52e73442deaedccf9.

**Comment by hutchig** [comment]
I can report that adding "andAwait" fixes the problem :-) 

Thank you so much Clement! @cescoffier 

Very glad to see this, I had thought it was a threading issue and was scratching my head as eventually I had inlined all the `@Before` and `@After` methods and replaced instance  variables with method ones and the problem was still there (just now).

I wonder if the io.vertx.mutiny.core.Vertx.close()
method might be one of these cases where single result not being a Publisher
is most useful, perhaps some users might expect close() would initiate the closing even if it did not wait for it. I notice the javadoc of close and closeAndAwait don't clarify it
http://smallrye.io/smallrye-reactive-utils/apidocs/io/vertx/mutiny/core/Vertx.html#close--
 
Thanks to you. I am so glad to pop this off my stack

**Comment by cescoffier** [comment]
> I wonder if the io.vertx.mutiny.core.Vertx.close()
method might be one of these cases where single result not being a Publisher
is most useful, perhaps some users might expect close() would initiate the closing even if it did not wait for it. 

It's not a Publisher, it's a Uni. Uni does not implement Publisher because we don't believe it makes sense for this type (1 signal). 

`Vert.x close()` is actually async, which means that it would have happened "after the fact". Even in bare Vert.x, it is recommended to not use `vertx.close()` but use the version taking a handler to be notified when Vert.x is actually closed (and resources are available). It is particularly important if you start servers or clients which would be automatically closed when Vert.x is closed.

Your comment about the Javadoc is very good and we should fix this (right now I believe it's just the Javadoc from the base method). I've opened https://github.com/smallrye/smallrye-reactive-utils/issues/145.

**Comment by hutchig** [comment]
Sorry I was not clear and thank you for clarifying. I know Uni it is not a Publisher, it was just when you said above "and no one subscribes" I missunderstood that you were implying that the close action was not in effect until some subscribe action in the chain somewhere had happened and that was not occurring. I understand now that the close would have happened in the background, just that the new Vertx instances are being created faster by Junit than they are going away.

**Comment by cescoffier** [comment]
Fixed by #576
