### ISSUE TITLE
ClassCastException when a nacked message is sent to the DLQ

### ISSUE THREAD

**Issue by geniusit** [smallrye/smallrye-reactive-messaging#675]
The failure strategy 'dead-letter-queue' seems to be broke.

Here is my configuration : 

Producer code : 

```
mp.messaging.outgoing.generated-price.connector=smallrye-kafka
mp.messaging.outgoing.generated-price.topic=prices
mp.messaging.outgoing.generated-price.value.serializer=org.apache.kafka.common.serialization.IntegerSerializer
```

```java
@Outgoing("generated-price")
    public Flowable<Integer> generate() {

        return Flowable.interval(5, TimeUnit.SECONDS)
                .map(tick -> random.nextInt(100));


    }
```

Consumer code : 

```
mp.messaging.incoming.prices.connector=smallrye-kafka
mp.messaging.incoming.prices.bootstrap.servers=localhost:9092
mp.messaging.incoming.prices.value.deserializer=org.apache.kafka.common.serialization.IntegerDeserializer
mp.messaging.incoming.prices.group.id=prices-group-local
mp.messaging.incoming.prices.client.id=prices-client-local
mp.messaging.incoming.prices.enable.auto.commit=false
mp.messaging.incoming.prices.failure-strategy=dead-letter-queue
```

```java
@Incoming( "prices" )
    @Outgoing( "double-prices" )
    @Acknowledgment(Acknowledgment.Strategy.POST_PROCESSING)
    public Uni< Integer > consume( final Integer price) {

        log.info("incoming message {}", price);
    
        if(price< 50) {
            return Uni.createFrom().item(price* 2);
        }
        else {
            return Uni.createFrom().failure(new Exception("Price has to be < 50"));
        }
    }
```

I got the following stacktrace when the price is >= 50 : 

```java
2020-07-21 14:19:07,770 ERROR [io.sma.rea.mes.kafka] (vert.x-eventloop-thread-8) SRMSG18207: Unable to dispatch message to Kafka: java.lang.ClassCastException: io.vertx.kafka.client.producer.RecordMetadata cannot be cast to java.lang.Void
        at io.smallrye.context.SmallRyeThreadContext$ContextualFunction.apply(SmallRyeThreadContext.java:76)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
        at io.smallrye.mutiny.operators.UniSubscribeToCompletionStage$2.onItem(UniSubscribeToCompletionStage.java:44)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
        at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribing$1(AsyncResultUni.java:34)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.lambda$send$8(KafkaProducerImpl.java:160)
        at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.lambda$null$1(KafkaWriteStreamImpl.java:118)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

The application stops to consume new messages and the lag is increasing.

I notice that when I lauch this command : 
```
kafka-console-consumer -bootstrap-server localhost:9092 --topic dead-letter-topic-prices
```
I see an incoming message so the DLQ is correctly populated. 

I use quarkus 1.6

Java : 
λ java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

**Comment by cescoffier** [comment]
I've found the issue, fixing...

**Comment by cescoffier** [comment]
@geniusit See https://github.com/smallrye/smallrye-reactive-messaging/pull/676.
