### ISSUE TITLE
Issues While Connecting To GCP Pub/Sub

### ISSUE THREAD

**Issue by kdpatel1993** [smallrye/smallrye-reactive-messaging#858]
Currently, I am trying to use same example of GCP pub/sub quick-start. as per example set the publisher and receiver like following,

microprofile-config.properties:

gcp-pubsub-project-id=krunal-gcp

Google Cloud Pub/Sub sink (we write to it)
smallrye.messaging.sink.my-channel.connector=smallrye-gcp-pubsub
smallrye.messaging.sink.my-channel.topic=test-services

Google Cloud Pub/Sub source (we read from it)
smallrye.messaging.source.my-topic.connector=smallrye-gcp-pubsub
smallrye.messaging.source.my-topic.topic=test-services
smallrye.messaging.source.my-topic.subscription=test-workers

As sender of message:

`@Inject
	@Channel("my-channel")
	Emitter<String> emitter;`

	public void periodicallySendMessage() {
		final AtomicInteger counter = new AtomicInteger();
		Executors.newSingleThreadScheduledExecutor().scheduleAtFixedRate(() -> {
			String message = "Hello " + counter.getAndIncrement();
			System.out.println("Emitting: " + message);
			emitter.send(message);
		}, 5, 10, TimeUnit.SECONDS);
	}

As receiver of message:

`   @Incoming("my-topic")`
   
 `
	public CompletionStage<Void> consume(final PubSubMessage message) {
		System.out.println("received (my-topic): " + message.getPayload());
		return message.ack();
	}
`

I try to run this example facing error 
Results in: 
`Exception in thread "main" java.lang.NoSuchMethodError: javax.enterprise.inject.spi.ObserverMethod.getPriority()I
	at org.jboss.weld.resolution.TypeSafeObserverResolver$ObserverMethodComparator.compare(TypeSafeObserverResolver.java:55)
	at org.jboss.weld.resolution.TypeSafeObserverResolver$ObserverMethodComparator.compare(TypeSafeObserverResolver.java:46)
	at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.ArrayList.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at org.jboss.weld.resolution.TypeSafeObserverResolver.sortResult(TypeSafeObserverResolver.java:106)
	at org.jboss.weld.resolution.TypeSafeObserverResolver.sortResult(TypeSafeObserverResolver.java:44)
	at org.jboss.weld.resolution.TypeSafeResolver$ResolvableToBeanCollection.apply(TypeSafeResolver.java:52)
	at org.jboss.weld.resolution.TypeSafeResolver$ResolvableToBeanCollection.apply(TypeSafeResolver.java:43)
	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.lambda$null$0(ReentrantMapBackedComputingCache.java:55)
	at org.jboss.weld.util.LazyValueHolder$1.computeValue(LazyValueHolder.java:32)
	at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:46)
	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:72)
	at org.jboss.weld.resolution.TypeSafeResolver.resolve(TypeSafeResolver.java:88)
	at org.jboss.weld.event.ObserverNotifier.resolveObserverMethods(ObserverNotifier.java:147)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
	at org.jboss.weld.bootstrap.events.AbstractDefinitionContainerEvent.fire(AbstractDefinitionContainerEvent.java:44)
	at org.jboss.weld.bootstrap.events.BeforeBeanDiscoveryImpl.fire(BeforeBeanDiscoveryImpl.java:54)
	at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:407)
	at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:79)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:802)`

 Used Java version: 8, windows

**Comment by cescoffier** [comment]
It looks like a weird Weld versioning issue. @manovotn Any idea?

On which environment are you deploying? 
@loicmathieu was able to get it running last week on Quarkus.

**Comment by loicmathieu** [comment]
Yes, I was able to make it works on Quarkus, see https://github.com/loicmathieu/google-cloud-services/tree/feat/pubsub-reactive-messaging/integration-tests/smallrye-reactive-messaging-pubsub

I only tested an `@Incoming` and on Java 11.

This indead looks like a CDI issue.

**Comment by manovotn** [comment]
Hmm, this looks like you are trying to use Weld 3.x (or newer) with CDI 1.2? @kdpatel1993, can you double check your versions and post it here, please?

Because [`ObserverMethod.getPriority()`](https://github.com/eclipse-ee4j/cdi/blob/2.0/api/src/main/java/javax/enterprise/inject/spi/ObserverMethod.java#L85-L96) is something that was added in CDI 2.0.
Weld 3 relies on that and uses it [here in the code](https://github.com/weld/core/blob/3.1/impl/src/main/java/org/jboss/weld/resolution/TypeSafeObserverResolver.java#L53-L55).

**Comment by kdpatel1993** [comment]
Yes @manovotn I am using Weld 3.1.3.Final with CDI 1.1.
let me update the version of CDI and try it again. 
thanks for update.

**Comment by kdpatel1993** [comment]
Hi @manovotn I have updated the version of CDI. Now i m facing 'Unsatisfied dependencies for type PubSubManager'.
Can you help here? which dependency I am missing here now?
Error screenshot: 
`org.jboss.weld.bootstrap.MissingDependenciesRegistry handleResourceLoadingException
INFO: WELD-000119: Not generating any bean definitions from io.smallrye.reactive.messaging.metrics.MetricDecorator because of underlying class loading error: Type org.eclipse.microprofile.metrics.MetricRegistry not found.  If this is unexpected, enable DEBUG logging to see the full error.
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type PubSubManager with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private io.smallrye.reactive.messaging.gcp.pubsub.PubSubConnector.pubSubManager
  at io.smallrye.reactive.messaging.gcp.pubsub.PubSubConnector.pubSubManager(PubSubConnector.java:0)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:375)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:287)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:140)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:161)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:63)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:61)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)`

**Comment by manovotn** [comment]
I am not familiar with it, but a quick search on this repo shows me the class is [here](https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-gcp-pubsub/src/main/java/io/smallrye/reactive/messaging/gcp/pubsub/PubSubManager.java). Therefore I _guess_ you are missing `smallrye-reactive-messaging:smallrye-reactive-messaging-gcp-pubsub`.

**Comment by manovotn** [comment]
Closing this issue as it was a user setup error and it was explained.
